### ISSUE TITLE
WebpackBin links are not working

### ISSUE THREAD

**Issue by moltar** [jarvelov/vue-form-json-schema#1]
Hey, first of all, great work! This is especially super useful for SSR stuff and being able to reuse JSON schema on both sides.

Want to note that WebpackBin links in the README seem to be down.

Thanks.

**Comment by jarvelov** [comment]
Fixed in https://github.com/jarvelov/vue-form-json-schema/commit/f61ad44af633fafcfdd72ea7110d01c4b48d77ad
