### ISSUE TITLE
Vue components demo incorrectly claims that 'input' is only v-model event supported

### ISSUE THREAD

**Issue by jettway** [jarvelov/vue-form-json-schema#10]
I've been using 'change' successfully. I can't find anywhere in the code that enforces 'input' only.

**Comment by jarvelov** [comment]
I think you mean this text:

> Vue version 2.20+ allows components using v-model to use another event type than input, which can be anything such as change, update or similar. The standard is input though and I haven't come across many components published on NPM which deviate from this standard. Unfortunately there is no support to use these components in vue-form-json-schema at the moment. However, this is coming soon

Yeah that's true, it is and always has been supported to use other events, like `change`, `update` etc.
I think I was meaning to mention that the component gets passed a `value`prop, and it is this prop that can not be renamed.

So for example if you wanted to have the `value` prop passed to the `myCustomComponentProp` then you couldn't, as of right now. I have updated this text, thank you.
