### ISSUE TITLE
how to pass anything to a custom component so that it isn't automatically applied to all child elements

### ISSUE THREAD

**Issue by vesper8** [jarvelov/vue-form-json-schema#106]
Hi there, I'm really enjoying using your library although I think I'm using it in a non-conventional way.

Rather then build the entire tree of html elements using the UISchema, I'm using custom components which themselves have a tree of html elements. So a custom component of mine might be

`div > label, input`

Right now the problem I'm having is that I would like to be able to define a label property as well as properties that I want applied to my input

If I do something like this

```
          uiSchema: [
            {
              component: 'my-custom-input-component',
              model: 'name',
              fieldOptions: {
                label: 'Enter your name',              
                attrs: {
                  placeholder: 'Your name',
                },
              },
            },
          ],

```

Then the label and placeholder will be applied to all 3 of my elements.. the div, the label and then input.

What I would want is to be able to pick from the uischema manually inside my custom component and not have any of this automatic-property-setting magic

So something like this

```
<template>
  <div class="tw-flex tw-flex-col tw-my-2">
    <label :for="vfjsFieldId">
      {{ $something.label }}
    </label>
    <input
      :id="vfjsFieldId"
      type="text"
      :value="vfjsFieldModel"
      :placeholder="$attrs.placeholder"
      class="tw-w-2/3"
      @input="setModel($event.target.value)"
    >
  </div>
</template>
```

How can I make use of `$something` in the above case ? Would props be the answer here? I haven't figured out how to use props yet with this library

**Comment by vesper8** [comment]
Hrm.. ok I just figured out how to use props.. wasn't hard at all.. my bad.. so I guess this is the ideal way of doing what I want?

**Comment by jarvelov** [comment]
Hi,

Yes, using props would be the easiest way to do this. Just move the `label` and `placeholder` properties inside `fieldOptions.props` and it will be passed as props to your component.

```js
{
  ...
  fieldOptions: {
    props: {
      label: 'Enter your name', 
      placeholder: 'Your name',
    },
  }
}
```

Then in your component:

```js
{
  name: "my-custom-input-component",
  props: ["label", "placeholder"]
  ...
}
```

```html
<template>
  <div class="tw-flex tw-flex-col tw-my-2">
    <label :for="vfjsFieldId">
      {{ label }}
    </label>
    <input
      :id="vfjsFieldId"
      type="text"
      :value="vfjsFieldModel"
      :placeholder="placeholder"
      class="tw-w-2/3"
      @input="setModel($event.target.value)"
    >
  </div>
</template>
```

**Comment by vesper8** [comment]
Thank you!
