### ISSUE TITLE
Load Schema trough GET

### ISSUE THREAD

**Issue by pitw** [jarvelov/vue-form-json-schema#12]
I'm trying to load Schema as plain JSON through a GET - Request.

With Example one I tried sth like this:

```
export default {
  name: 'example-one',
  components: {
    'vue-form-json-schema': VueFormJsonSchema,
    'pretty-print': PrettyPrint
  },   data () {
        return { json: null }
    },
  methods: {
    onChange(value) {
      this.model = value;
    },
    onChangeState(value) {
      this.state = value;
    },
    onValidated(value) {
      this.valid = value;
    },
  },
    mounted () {
        $.getJSON('http://localhost:8000/schema', json => {
            this.json = json
        })
    }
};
```
However I always get "TypeError: (intermediate value)(intermediate value)(intermediate value).reduce is not a function..."

Is this possible?

**Comment by jarvelov** [comment]
Loading the schema async should work perfectly fine as long as you provide the component with a placeholder value in the mean time. i.e. an empty object for `model`/`schema` and an empty array for `uiSchema`

Could you provide an example showing the error you're getting?

I threw together an example of loading schema/uiSchema/model from an API which works as expected: https://codesandbox.io/s/2p51q8q14y

Feel free to modify the example to show the error you're getting.

**Comment by pitw** [comment]
Thanks.
I've adapted the example with loading some JSON from a public API through axios:
[https://codesandbox.io/s/mjoxyz324y](https://codesandbox.io/s/mjoxyz324y)

Why I'm getting the   "0": {}, in Model  / Console error: "Invalid prop: type check failed for prop "model". Expected Object, got Array ...:"

**Comment by pitw** [comment]
Finally got it working... ;)
There was a problem with axios and resolve (resolve seems to be needed in this case, axios usually return one itself)

[https://codesandbox.io/s/mjoxyz324y](https://codesandbox.io/s/mjoxyz324y)
