### ISSUE TITLE
Using Event listener in JSON

### ISSUE THREAD

**Issue by pitw** [jarvelov/vue-form-json-schema#13]
As already explained in Issue  #12  I'm trying to load a complete form through JSON. 
Mainly it works now - but I'm wondering if its possible to load an event listener through JSON.

**Example:**
I need to make sure that Username (in model, not just in form) is always uppercase.
So accordingly to [the docs](https://jarvelov.gitbook.io/vue-form-json-schema/api/vue-form-json-schema/ui-schema/field/field-options/native-on) I'm doing sth like this (in JSON which is loaded on page load):

```
 "uiSchema": {
     "component": "input",
     "model": "username",
      "fieldOptions": {
        "nativeOn": {
          "input": "event => String(event.target.value).toUpperCase();"
        }
      }
    }
```

Probably its not meant to be used in this way (does it even get evaluated?) - but if its possible I'd appreciate a hint.

**Comment by jarvelov** [comment]
Sorry that I took so long to respond. I realize this is probably not of any help to you now as you've probably moved on but for anyone else that comes looking I'd like to point out a way to achieve this as it hasn't been documented yet.

As you noticed, ` "event => String(event.target.value).toUpperCase();"` in your example is just a string and it will be parsed as that, just a string. It isn't possible to get executable code from JSON, unless you're willing to use unsafe methods. However we can do this the "Vue way" by using a custom component to handle the uppercase conversion for us.

What isn't documented yet is that `vue-form-json-schema` actually accepts another prop: `components`. We can pass in custom components to this prop and then use them as any other globally registered component or native element.

Lets create a component to wrap a normal input and then handle the conversion to uppercase, like this:

```js
// InputWrapper.vue
<template>
  <input :value="value" @input="onInput">
</template

<script>
export default {
  name: 'InputWrapper',
  props: ['value'],
  methods: {
    onInput(event) {
      this.$emit('input', String(event.target.value).toUpperCase());
    }
  }
}
</script>
```

And then we can use it in `vue-form-json-schema` like so:

```js
// Import the InputWrapper component
import InputWrapper from './InputWrapper.vue'

export default {
  data: {
    // Create a data property to hold custom components
    components: {
      'input-wrapper': InputWrapper,
      // Or just: 
      // InputWrapper
    },
    // Use the same name as the key in the data.components,
    uiSchema: [{
      // Or: component: 'InputWrapper' if you didn't give the component a specific name in data.components
      component: 'input-wrapper',
      model: 'username'
    }],
    model: {}
  },
  methods: {
    onChange (model) {
      this.model = model
    }
  }
}
...

<template>
  <vue-form-json-schema
    :components="components"
    :model="model"
    @change="onChange"
  />
</template>
```
