### ISSUE TITLE
uiSchema components props reactivity

### ISSUE THREAD

**Issue by pierreben** [jarvelov/vue-form-json-schema#16]
When creating dynamically a uiSchema including components with props:

```
// A custom component
Vue.component('my-custom-component', {
  name: 'my-custom-component',
  props: ['message'],
  template: '<span>{{ message }}</span>'
})

...

data() {
  return {
    uiSchema:[],
    componentMessage: '',
  }
}

...

mounted: function() {
    this.uiSchema.push({
      component: 'my-custom-component',
      fieldOptions: {
        props: {
          message: this.componentMessage
        }
      }
    })
  }
```
The reactivity of componentMessage is unfortunately lost when its value changes.
The only workaround looks to re-generate the whole uiSchema when the componentMessage value changes.

Is there anything I'm missing about components props reactivity ?

**Comment by jarvelov** [comment]
If you want the `uiSchema` to be updated when `componentMessage` is updated you should have `uiSchema` be a computed property like this:

```js
...
computed: {
  uiSchema () {
    return [{
      component: 'my-custom-component',
      fieldOptions: {
        props: {
          message: this.componentMessage
        }
      }
    }]
  }
}
```

This way whenever `componentMessage` changes Vue sees that `uiSchema` uses the value of `componentMessage` and will  'recompute' the `uiSchema` property.

You can see an example of this here: https://codesandbox.io/s/pw858qo5lm

**Comment by pierreben** [comment]
Thank you so much to the answer, it's working properly.
Just a precision, do you think it can be a performance issue to re-gen the uiSchema in case of a form having an important number of fields ?

**Comment by jarvelov** [comment]
Whenever the `uiSchema` is changed (or any other prop which can affect anything visible for that matter) `vue-form-json-schema` generates a hash for each field which is then used as the `key` property for the field (which is what Vue uses to determine when something should be re-rendered). Rendering is the most performance sensitive part and is always done in the main thread and whenever possible one should strive to avoid. However, you should be able to handle several hundred fields without any noticeable delay, given that they do not all update at once.

Here's an updated version of the previous example with 100 fields using the custom component: https://codesandbox.io/s/201x1v9m1r

 In this example the custom components' all rely on the`componentMessage` `model` and each time it is updated they will all re-render. Notice the difference between when you type into the first input field compared to the second input field. When you type into the second input field the fields using the custom component will re-render.

You can try increasing the number in the loop of `componentMessage` from 100 to 200, 300 etc to see when you notice any lag. However if you have several hundred fields which all should update when for example an input is updated you will run into performance issues.

**Comment by pierreben** [comment]
@jarvelov, Thank you for these extremely accurate and complete explanations !
