### ISSUE TITLE
Conditionally required fields

### ISSUE THREAD

**Issue by miguelzapaton** [jarvelov/vue-form-json-schema#17]
First of all, VFJS is awesome!

I just had a new use case where some fields in the schema are conditionally required. 

In order to demonstrate it I adopted example #1 to #1' here: 

https://codesandbox.io/s/8xl2r1k6o8

As you can see it uses if then else from DRAFT-7. Validation by ajv is done correctly. state.vfjsErrors shows the errors as it should. 

However the required fields are not marked dynamically.

I think it's related with the initialization 'hack' for the required fields here:

https://github.com/jarvelov/vue-form-json-schema/blob/master/src/vfjs-global-mixin/methods/vfjs-validation/index.js

As it's done nly once and with an empty model the required state attrs are not updated when the model changes. I was just seeing that there's already a TODO in there. 

***++*** from me for this feature.

I can try a PR but I would have to get in deeper first...

**Comment by jarvelov** [comment]
Hey thanks, and thanks for the feature request!

As you have discovered the required 'hack' is only calculated once during initialization and sadly I haven't gotten around to fix it. However, it should be pretty straight forward to recalculate when state/model changes, I'll look into it tonight.

**Comment by jarvelov** [comment]
Just an update: I've implemented the logic to update the required fields and am now in the process of evaluating any performance issues. I hope to release a new version by the end of the week.

**Comment by jarvelov** [comment]
Feature added in `v2.4.0`. See [Example 6](https://4rykx7jj19.codesandbox.io) and inspect the source code to see it in action.
