### ISSUE TITLE
Example for lists (`type:array`)

### ISSUE THREAD

**Issue by luhmann** [jarvelov/vue-form-json-schema#18]
I am trying to figure out how one would implement a `uischema` for a jsonschema `array`-type.

Lets assume you have a schema-like this:

```json
{
   "$id":"https://example.com/arrays.schema.json",
   "$schema":"http://json-schema.org/draft-07/schema#",
   "type":"object",
   "properties":{
      "vegetables":{
         "type":"array",
         "items":{
            "veggie":{
               "type":"object",
               "required":[
                  "veggieName",
                  "veggieLike"
               ],
               "properties":{
                  "veggieName":{
                     "type":"string",
                     "description":"The name of the vegetable."
                  },
                  "veggieLike":{
                     "type":"boolean",
                     "description":"Do I like this vegetable?"
                  }
               }
            }
         }
      }
   }
}
```
(taken from [the official docs](http://json-schema.org/learn/miscellaneous-examples.html), but simplified to not include references)

I can see how I can create a `uischema` that renders the array-component like this:

```json
[
   {
      "model":"vegetables",
      "component":"app-item-list"
   }
]
```

And I am fine to build any logic I need for maintaining the list (add, delete, reorder items, etc.) inside the component `app-item-list`. But what I cannot figure out is how I can define in the `uimodel` that I want `veggieName` rendered as component `app-input` and `veggieLike` as component `app-checkbox`.

Is this currently supported. Thanks in advance for any pointers.

**Comment by jarvelov** [comment]
Here's an example of what I think you're trying to do: https://codesandbox.io/s/542nqvq6yx

Unfortunately the documentation around a lot of the stuff I used to make this example is non-existent, however the API is stable and it is very much safe to use.

Basically we're using a `vue-form-json-schema` to render the `app-list-item` component which itself renders another `vue-form-json-schema` for each vegetable in the vegetables array.

The hierarchy can be represented like this:

    vue-form-json-schema
       -> app-list-item (v-for)
           -> vue-form-json-schema (0)
             -> b-form-radio-group
           -> vue-form-json-schema (1)
             -> b-form-radio-group

Every component with a `model` gets passed a lot of [props](https://github.com/jarvelov/vue-form-json-schema/blob/master/src/vfjs-field-mixin/props.js) when rendered. If we add these props to our component we can use them to get passed the `schema` and `uiSchema` via the props.

We first use the `vfjsChildrenUiSchema`which is the `uiSchema` for the `app-item-list` component's `children`. Then we use `vfjsFieldSchema` to get access to this field's json schema. Then we use those props to render a `vue-form-json-schema` component for each item in the `value`prop, which is the `app-item-list` component's model value (the vegetables array).

**Comment by luhmann** [comment]
Thank you for your very quick answer. Your solution works perfectly for my use-case. 

In case you want to turn it into an example I made a slight mistake in the schema when removing the reference from linked example in the documentation. Its dereferenced version would actually not include the `veggie`-key. Like this: https://codesandbox.io/s/4jkwrvvoz7

Feel free to close the issue.

**Comment by jarvelov** [comment]
That's great to hear. Glad we could make it work.

I think I won't add this as an example because I think this is something `vue-form-json-schema' should handle. I think I'll introduce something like this:

```js
uiSchema () {
return [{
  component: 'app-item-list',
  model: 'vegetables',
  loopModel: true, // or 'repeatModel', or something, name not determined yet
  children: [...]
}
```

And then just have `vue-form-json-schema` loop over the model and do what `app-item-list` does in our example.

**Comment by sigalalg1** [comment]
> Here's an example of what I think you're trying to do: https://542nqvq6yx.codesandbox.io/
> 
> Unfortunately the documentation around a lot of the stuff I used to make this example is non-existent, however the API is stable and it is very much safe to use. I'll try to update it soon.
> 
> Basically we're using a `vue-form-json-schema` to render the `app-item-list` component which itself renders another `vue-form-json-schema` for each vegetable in the vegetables array.
> 
> The hierarchy can be represented like this:
> 
> ```
> vue-form-json-schema
>    -> app-list-item (v-for)
>        -> vue-form-json-schema (0)
>          -> b-form-radio-group
>        -> vue-form-json-schema (1)
>          -> b-form-radio-group
> ```
> 
> Every component with a `model` gets passed a lot of [props](https://github.com/jarvelov/vue-form-json-schema/blob/master/src/vfjs-field-mixin/props.js) when rendered. If we add these props to our component we can use them to get passed the `schema` and `uiSchema` via the props.
> 
> We first use the `vfjsChildrenUiSchema`which is the `uiSchema` for the `app-item-list` component's `children`. Then we use `vfjsFieldSchema` to get access to this field's json schema. Then we use those props to render a `vue-form-json-schema` component for each item in the `value`prop, which is the `app-item-list` component's model value (the vegetables array).

Hi @jarvelov  
We are using vue-form-json-schema, and it is very useful for us, so thank you for all your effort!
I am trying to use this example in vue3, and for some reason, I found out that self defined components with children, do not get their child schema and ui schema in vue3.
This is at least what happens when I use the same example in vue3.
Any idea what I am missing? 

Thanks!
Sigal
