### ISSUE TITLE
Examples on how to integrate with bootstrap-vue or other packages

### ISSUE THREAD

**Issue by moltar** [jarvelov/vue-form-json-schema#2]
Would be helpful to see a brief example on how to integrate this with third party component libraries. I understand that it is possible to pass a component name to get a custom component instead of `input`. But the problem is with the rest of the wiring.

For example, in `bootstrap-vue` a common piece of code might be:

```html
        <b-form-group
          id="email"
          label="Email"
          label-for="email">
          <b-form-input
            id="email"
            v-model.trim="email"
            required
            type="text"
          />
        </b-form-group>
```

Notice that everything is wrapped into `b-form-group` and also other components can be added to `b-form-group`, such as error messages or help hints.

If you could throw together a few quick examples, I can create a doc PR for this.

Docs for `bootstrap-vue`: https://bootstrap-vue.js.org/docs/components/form-input

Thanks.

**Comment by moltar** [comment]
The only solution I can come up with so far is to create another layer or custom components that then wrap `bootstrap-vue` components and pass config down via attributes.

**Comment by jarvelov** [comment]
Added demo showing how to use Vue components: https://github.com/jarvelov/vue-form-json-schema/commit/b91bb15f339b5e2ca45468f16eb22e19530d2cf4
