### ISSUE TITLE
Update Readme example

### ISSUE THREAD

**Issue by sbc3** [jarvelov/vue-form-json-schema#24]
Hi,

The example in the readme is out of date and doesn't work. The component snippet doesn't match what is in the linked examples.

Once notable difference is that the Readme version hooks up the change event with `:on-change="onChange"` which is wrong and doesn't match the linked example.

Suggest that it's either updated or removed. Otherwise a really handy package 👍

**Comment by jarvelov** [comment]
Glad you like vue-form-json-schema! Thank you for letting me know about this problem! I will go over the documentation and demos and fix it.

**Comment by jarvelov** [comment]
The README has now been fixed and the documentation has been updated as well.
