### ISSUE TITLE
Nested schema displays permanent field error

### ISSUE THREAD

**Issue by DevMedicitv** [jarvelov/vue-form-json-schema#27]
errorOptions doesn't works well with nested schema.
Once edited a field remains permanently in error state while the the full model is validated.

https://codesandbox.io/s/example-6-j711q

Issue seems to be in VFJS_EVENT_FIELD_MODEL_VALIDATE, where the field validation schema doesn't handle correctly nested key like user.firstName

**Comment by jarvelov** [comment]
Hi, thanks for reporting. I'll investigate and report back.

**Comment by jarvelov** [comment]
I've added a fix for this in #28
I'll merge this tomorrow as it's getting late.

**Comment by jarvelov** [comment]
#28 has now been merged.

Another example has been added which shows nested properties in action: https://nxn8y.codesandbox.io/
