### ISSUE TITLE
How to create checkbox and save multiples checks

### ISSUE THREAD

**Issue by Pefeli** [jarvelov/vue-form-json-schema#29]
Hi, I'm trying to create a couple of checkboxes, the render it's ok, but when I check more than one, in the model object only save the last one.

Here is part of code in ui schema

uiSchema = [
{                            
    'component': 'input',
    'model': 'answer',
    "valueProp": "checked",
    'fieldOptions': {
        'attrs': {
            'id': 'id1',
            'type': 'checkbox'
        }, 
        'domProps': {
            'value': 'value1'
        },
        'on': 'change'
    }                                                    
},
{
    'component': 'label',
    'fieldOptions': {
        'attrs': {
            'for': 'id1'
        },
        'class': [
            'custom-control-label'
        ],
        'domProps': {
            'innerHTML': 'Value 1'
        }
    }
},
{                            
    'component': 'input',
    'model': 'answer',
    "valueProp": "checked",
    'fieldOptions': {
        'attrs': {
            'id': 'id2',
            'type': 'checkbox'
        }, 
        'domProps': {
            'value': 'value2'
        },
        'on': 'change'
    }                                                    
},
{
    'component': 'label',
    'fieldOptions': {
        'attrs': {
            'for': 'id2'
        },
        'class': [
            'custom-control-label'
        ],
        'domProps': {
            'innerHTML': 'Value 2'
        }
    }
}
]

**Comment by jarvelov** [comment]
Hi, I'm sorry that I haven't replied earlier. I'll post an example of how to accomplish this later this evening.

**Comment by Pefeli** [comment]
> Hi, I'm sorry that I haven't replied earlier. I'll post an example of how to accomplish this later this evening.

Thanks dude, I appreciate it.

**Comment by jarvelov** [comment]
Se this example: https://codesandbox.io/s/example-6-lclh4

It is currently only possible to achieve this by using a javascript function to handle the change event.

**Comment by Pefeli** [comment]
> Se this example: https://codesandbox.io/s/example-6-lclh4
> 
> It is currently only possible to achieve this by using a javascript function to handle the change event.

Thanks a lot, it worked like a charm.
