### ISSUE TITLE
Can't get "Basic example with one field" to run

### ISSUE THREAD

**Issue by moltar** [jarvelov/vue-form-json-schema#3]
Copy-pasted it verbatim and compiles fine, and renders the input. However, typing anything into the input field does not update the model.

It looks like `onChange` method is not firing at all.

Any ideas?

**Comment by moltar** [comment]
With Vue Chrome plugin I can see that event is being fired with the correct payload:

```
name:"VFJS_EVENT_FIELD_MODEL_UPDATE"
type:"$emit"
source:"<Root>"
payload:Array[1]
0:Object
key:"firstName"
value:"asdasdk"
```

**Comment by moltar** [comment]
A full list of events firing after typing just a single letter "a": http://take.ms/htmKF

**Comment by jarvelov** [comment]
Hey, sorry for the delay and thanks for taking the time and opening not only 1 but three separate issues! I'll be looking into another host for the demos and see if I can replicate the bugs you've posted. I'll be revisiting this plugin anyway this week to fix https://github.com/jarvelov/vue-form-json-schema/issues/4

**Comment by jarvelov** [comment]
It's been several versions since this issue was posted and vue-form-json-schema has been stable for a long time now so I can confidently say that this is fixed by now.
