### ISSUE TITLE
errorHandler behaviour

### ISSUE THREAD

**Issue by miguelzapaton** [jarvelov/vue-form-json-schema#31]
Hi again,

good to see that VFJS makes some progress from time to time. 

I was wondering if the behaviour of the errorHandler is as intended. 
For demo I just prepared a variation of Example 1:

https://4xz3s.csb.app

When I enter a text longer than 3 chars the red error div appears. -> OK

When I know delete the chars with backspace:

- First the error div gets deleted -> OK
- But when the field is empty again, the red margin of the empty div box re-appears even if valid is true. -> ?

I thought that when valid is true the errorHandler components would never be rendered.

Any hint?

Miguel

**Comment by jarvelov** [comment]
Hi,

Thanks for reporting this. I have reproduced the error. This behavior is not intended, this looks like it is a bug in VFJS, it should be pretty easy to fix.

I'll report back when I've found what's causing it.

**Comment by jarvelov** [comment]
Hi,

A fix was added in v2.3.5. You can see the intended behavior in action here: https://7k1r2.csb.app/

**Comment by miguelzapaton** [comment]
Great. Thank you very much!
