### ISSUE TITLE
2.4.0 validation behaviour

### ISSUE THREAD

**Issue by miguelzapaton** [jarvelov/vue-form-json-schema#34]
Hi Tobias,

after I saw that you changed the validation behaviour (-> Conditionally required fields - Yepeeah) I updated my app to 2.4.0.

Before and with showValidationErrors: true the model was validated on every event (e.g. in case of input on a text field with every character typed) and v-on:validated was fired quite often.

Now this does not seem to be the case. However validationOnLoad works as expected. 

Did I miss anything when upgrading to 2.4.0? 

Is there another way to fire the validation manually apart from re-setting the option showValidationErrors:true ?

Thank you very much for sharing this project!

Regards,

Miguel

BTW. It would be great to have some place for discussion. E.g. I would like to share experience about Vue SSR and VFJS.

**Comment by jarvelov** [comment]
Hi Miguel,

Ah, damn. I guess that I must have missed to confirm the old behavior. This is why I should write some tests...

Thank you for notifying me. I'll try to get a fix out as soon as I can.

I'd love to hear your experiences. My email is in my GitHub profile and you can reach me there.

**Comment by miguelzapaton** [comment]
Hi again,

When I switched back to 2.3.6 I noticed that the text entry was somewhat delayed in the form as for every character the full form validation was executed. Maybe you meant this when you mentioned performance concerns (https://github.com/jarvelov/vue-form-json-schema/issues/32#issuecomment-576897555) in the other thread.

In my case it would be perfect to have an vfjs API call to fire the validation manually.

Also the difference between the "validate" and "showValidationErrors" options is not so clear.

Regards,

Miguel

**Comment by jarvelov** [comment]
> When I switched back to 2.3.6 I noticed that the text entry was somewhat delayed in the form as for every character the full form validation was executed. Maybe you meant this when you mentioned performance concerns (#32 (comment)) in the other thread.

**Comment by jarvelov** [comment]
Hi @miguelzapaton 

I've just release `v2.5.0` in which the irregular validation behavior has been patched. Can you confirm if this solves the issues you were having?

Also, I am working on making some vfjs methods available, like validate. I'll keep you informed.

**Comment by miguelzapaton** [comment]
Hi Tobias,

Sorry for the delayed response. I now checked v2.5.3 and it works fine. 
The input still feels a bit laggy on my test computer but the form is perfectly usable. 

I think the best solution would be that the application could have a better control over when the validation happens. E.g. call a vfjs method on input leave or on a similar event.

Again, many thanks for sharing this project!

Regards,

Miguel

**Comment by jarvelov** [comment]
Hello again Miguel,

Glad to hear that it's working for you as expected, albeit with that performance issue.

I hope to provide in the next release a way to imperatively call the validation function from outside of the VFJS method.

I'll let you know here when it is available.
