### ISSUE TITLE
How to dynamically add items into array

### ISSUE THREAD

**Issue by OdiljonQurbon** [jarvelov/vue-form-json-schema#36]
Awesome project! Thanks for this great flexible tool. 

I'm trying to generate schema where I could add more items into array by clicking "Add More Fruits" button.

Here's an example: [Dynamically add more items to array](https://codesandbox.io/s/issue-18-1-de2yy)

How can I implement this functionality?

**Comment by jarvelov** [comment]
Hi,

There's many different ways to achieve this but given your example as the starting point you were very close to get it working. You added the `v-on:add-more` listener to the `<vue-form-json-schema>` component, however it doesn't emit that event, the `<app-item-list>` component does, all you need to do basically is to listen to that event in the uiSchema for the `app-list-item` component.

## Option 1

However, why not just reuse the `change` event in the addMore function inside `app-item-list`. Essentially just replace:

```js
this.$emit("add-more");
```

with

```js
this.$emit("change", [
  ...this.value,
  {
    fruitName: ""
  }
]);
```

This is by far the simplest as you don't have to deal with multiple events.
 See an example here: https://codesandbox.io/s/issue-18-1-tdlfj

You can use listeners for both events, but the `add-more` event would need to emit the field's new value just like the `change` event does.

## Option 2

As I noted at the start there are multiple ways to achieve the desired effect. You could also move the `v-btn` to up a level into the uiSchema of the top level `vue-form-json-schema` component. You can see example of this here: https://codesandbox.io/s/issue-18-1-um52k

## Option 3

Okay, but what if you want/need to use another event and can't expect the component to provide the new value for all events? Give me more flexibility! All right, I hear you!  All you need to do is use a callback listener in the field's `uiSchema`, as can be seen below.

```js
{
  component: "app-item-list",
  model: "fruits",
  fieldOptions: {
    on: {
      change: value => {
        // We always have to return the field's new value, otherwise it gets set to undefined
        return value;
      },
      "add-more": () => {
        // Merge the old values with the new item, if we just return the new item the old values will be lost
        return [...this.model.fruits, { fruitName: "" }];
      }
    }
  }
}
```

See an example here: https://codesandbox.io/s/issue-18-1-yw6ff

---

To provide a bit more of an explanation to what is happening above.

Normally we just use `on: ["change"]` and the field model is automatically updated when the component emits a `change`event, which might seem like magic. However what this does is add an `@change="setVfjsFieldModel"` listener on the field.

When we use an object like my example above for the `on` property we tell `vue-form-json-schema` to expect that every key in the object is a callback. So what this does is basically adding a listener that works like this instead: `@change="(value) => setVfjsFieldModel(callback(value)"`

So when the `change` event is emitted from the component it first gets sent to the callback, which is then set as the field's model.

It is very beneficial to use a callback when the emitted event data must be modified before it can be set as the field value. This is a good place to do formatting of for example phone numbers if you need to strip away or replace some characters.

**Comment by OdiljonQurbon** [comment]
Great answer! Thank you very much for this detailed explanation! You rock. 👍

**Comment by josvos** [comment]
Hi, as someone interested in starting to use VFJS I'm scanning the issues related to handling arrays, as this was something missing from the docs and examples (AFAICS).

I was wondering if there is no way to let a component from the `uiSchema` be rendered multiple times with a v-for and use the loop index in the model, like `model="fruits.$index"`or `model="fruits[$index]"`?  If you have a schema including some simple arrays (e.g. a person schema with an array of e-mail addresses or phone numbers per person), the above mentioned methods sound relatively heavy weighted.
