### ISSUE TITLE
Mismatching versions with npm

### ISSUE THREAD

**Issue by protostefano** [jarvelov/vue-form-json-schema#37]
Hi,
I have added your package in my npm dev dependency.
After build it was installed 2.5.0 version.
But in your tag release, this version isn't present.

**Comment by StefanoVollono** [comment]
me too

**Comment by jarvelov** [comment]
Hi, I'm terribly sorry, I must have forgotten to upload the tags when pushing the 2.5.0 release. I will correct this on Sunday.

Thank you for reporting this!
