### ISSUE TITLE
Custom components from Vue plugin not resolving

### ISSUE THREAD

**Issue by alexravenna** [jarvelov/vue-form-json-schema#39]
Hi! First off, I just want to say I'm a fan of this component, especially because of the separation between JSON and UI schemas and the ability to use custom components. 👍 

I'm a developer on a feature team working on part of a much larger product. I've been using this component for a few months in sort of my own "bubble" and haven't had any problems with it. However, now that I'm trying to integrate into the rest of the product I've run into an odd situation, which I hope I can describe appropriately.

I've wrapped your component in another component (ParameterEditor) that has some styling, automatically creates a UI schema from the JSON schema if none is present, etc. ParameterEditor is contained in a component library package that is consumed as a Vue plugin, similar to BootstrapVue. This library also contains other components, such as input components (one is called EditorField), that are used as custom components in UI schemas for the ParameterEditor.

When I consume the library plugin in my feature's module in a local `App.vue`+`main.ts` then I have no problems.

Here's how everything should really look (i.e. how it looks when I test it in just my feature):

![image](https://user-images.githubusercontent.com/29532881/75766395-60696a00-5d41-11ea-95c9-833718310b60.png)

And the corresponding Vue DevTools tree:

![image](https://user-images.githubusercontent.com/29532881/75775808-112c3500-5d53-11ea-9026-df4ce2cfd0f7.png)

In the product application, the library plugin is consumed through `Vue.use()`. This product application is supposed to have a modular nature, so my feature is _also_ installed as a Vue plugin through an `install()` function, which registers my feature's components to the product application. One of my components (lets call it MyParameterEditor 😆) uses ParameterEditor. So in the end, in the core application I have two plugins:
- my feature
- the component library

And my feature plugin uses some globally registered components from the library plugin, such as ParameterEditor.

When trying everything out in the product application (with `vue-cli-service serve`), the custom components I'm using in VueFormJsonSchema are somehow not resolved correctly. I get **no** console errors in the browser or at compile time, but the DOM looks like this:

![image](https://user-images.githubusercontent.com/29532881/75766361-534c7b00-5d41-11ea-8284-1b42d42bf34b.png)

As you can see, the <k-editor-field> custom components' templates don't get replaced by their actual content within them. Visually, nothing is displayed. The corresponding Vue Devtools tree also doesn't show the custom components. On a side note: not all of the custom components are wrapped in VueFormJsonSchemaFieldComponent, I assume because some don't use `model` in the UI schema?: 

![image](https://user-images.githubusercontent.com/29532881/75775599-982cdd80-5d52-11ea-9f70-4bc6737425f7.png)

I don't understand why this is happening 😓 . The custom component `<k-editor-field>` is obviously registered in Vue globally (because I get no errors saying it isn't in the browser console), so why isn't it getting resolved properly? It almost reminds me of the behavior of Web Components...

Do you have _any_ idea what could be going on here? Have you seen this before? I'd appreciate any help! 😇 

I'm sorry for not creating a CodeSandbox for this, but I've already spent a couple days trying to figure this out and our system is complicated enough that reproducing it (especially since I've never used CodeSandbox myself before) would take even longer. If I find the time though, I'll try!

**Comment by jarvelov** [comment]
Hi!

I see your problem, could you try to pass in the globally registered component to VFJS and see if this changes anything.

I'm on mobile so I hope you understand my example below:

```js
<vue-form-json-schema
  :components="components"
  // Other props
/>

...
import KEditorField from "../k-editor-field"

data() {
  return {
    "k-editor-field": KEditorField
  }
}
```

**Comment by jarvelov** [comment]
Also, please provide your Vue and VFJS version.

**Comment by alexravenna** [comment]
> Also, please provide your Vue and VFJS version.

Vue: 2.6.11
VFJS: 2.5.0

I'm going to try out your suggestion now.

**Comment by alexravenna** [comment]
> Hi!
> 
> I see your problem, could you try to pass in the globally registered component to VFJS and see if this changes anything.
> 
> I'm on mobile so I hope you understand my example below:
> 
> ```js
> <vue-form-json-schema
>   :components="components"
>   // Other props
> />
> 
> ...
> import KEditorField from "../k-editor-field"
> 
> data() {
>   return {
>     "k-editor-field": KEditorField
>   }
> }
> ```

Note: I think your `data()` is missing a `components` member. I'm used to the vue-class-component and vue-property-decorator syntaxes though, so it looks different in my code.

Anyway, huzzah! 🎉 🎉 🎉  It works!

Could you maybe explain what's happening here? The `components` prop isn't mentioned anywhere in the documentation nor in the Vue.js documentation 🤔. What about the nature of this plugin architecture causes this to be necessary?

This also makes VueFormJsonSchema a bit less flexible if components that may be used in it have to be passed in first since I can't change our plugin architecture, but beggars can't be choosers 😅.

**Comment by jarvelov** [comment]
Glad to see that it resolved the issue!

I haven't encountered this before and without seeing more code I'm not sure where the issue is, however, the issue you are experiencing is a bug.

If the components are globally registered then VFJS should render them as components. There might be some changes in how Vue resolves component in later versions, do you have different versions of Vue in your different environments?

Are your components resolved asynchronously?

The components property exists as not all components can/should be registered globally, there are edge cases. In these cases it is beneficial to be able to pass in components to VFJS directly when needed. 

If you can provide more information about your setup and code, or even better reproduce it on codesandbox, then I might be able to see why this is happening.

**Comment by alexravenna** [comment]
No, both environments are running the same version of Vue (2.6.11) and the components aren't resolved asynchronously.

I've started a CodeSandbox where I can hopefully reproduce the problem and I'll post back here if/when it's up.
