### ISSUE TITLE
Type array

### ISSUE THREAD

**Issue by leshiple** [jarvelov/vue-form-json-schema#40]
Please show an example with a field of type array of objects
[My schema](https://codesandbox.io/s/example-2-7je6j)
uiSchema - ?

**Comment by jarvelov** [comment]
Hi,

Maybe [this thread](https://github.com/jarvelov/vue-form-json-schema/issues/36) can be of help to you? As VFJS doesn't tell you how to set up your uiSchema, so how your uiSchema ends up depends on what components / elements you want to use.

Check out my answer and the code examples in the link above and you'll see fields of array objects. If this doesn't help please provide what kind of components/elements you want to use and I'll try to see if I can whip up an example for you.

Cheers!

**Comment by leshiple** [comment]
Thanks.
