### ISSUE TITLE
nativeOn/on cause model value changes

### ISSUE THREAD

**Issue by qtttttttttting** [jarvelov/vue-form-json-schema#47]
I bind keydown event to a method by nativeOn/on. When trigger the method, the model of this form item  will be the value that the method returns. I expect the model does not change.
I made an example: https://codesandbox.io/s/example-5-7k87m

**Comment by jarvelov** [comment]
Hi, I've looked through your code and saw some implementation errors.

Here's a working example: https://codesandbox.io/s/example-5-bdyjz

Some notes:

As you are using the Form component, which renders a form element, you don't need to handle the Enter event in the Input element. The form element will submit the form when the Enter key is pressed, so you only need to handle the submit event for the Form component.

```js
component: "Form",
fieldOptions: {
  props: {
    // Setting this is not required, the Form component from the `iview` package does not need this prop
    // Only set model if you want to listen to events from a component, see below
    model: this.model
  },
  nativeOn: {
    submit: this.submit
  }
}
```

As I've noted above you don't need to handle the Enter key in the Input component, but if you want to you need to handle the proper event. You can only listen to [native events](https://developer.mozilla.org/en-US/docs/Web/Events) in `nativeOn` or component events in `on`, which are emitted by the Vue component.

```js
{
  component: "Form-item",
  fieldOptions: {
    props: {
      prop: item.key,
      label: item.label
    }
  },
  children: [
    {
      component: item.component.name,
      model: item.key,
      fieldOptions: {
        // This is all that is needed here,
        nativeOn: ["input"]
      }
    }
  ]
};
```

Hope this helps!
