### ISSUE TITLE
Function calls in component props not working

### ISSUE THREAD

**Issue by janschoepke** [jarvelov/vue-form-json-schema#48]
Hi,
some Vue components may have function calls in their properties. Such as the QFile component of the open source library Quasar ([Link to library](https://quasar.dev/vue-components/file-picker#Restricting-files)): 

```
<q-file v-model="upload" label="Label" :filter="checkFileSize"></q-file>
```

Under the property ":filter" a function (in this case "checkFileSize") is passed. This function is defined in the Vue methods object. Unfortunately I have not yet found a way to call the function via the uiSchema. I have already tried: 

```
{
    component: "q-file",
    model: "upload",
    fieldOptions: {
        props: {
            ":filter": "checkFile"
            //or
          ":filter": checkFile
          //or
          ":filter": "this.checkFile"
          //or
          ":filter": this.checkFile
      }
   }
}
```

None of these solutions worked. Is there already a solution for this problem?

Building on this (and perhaps this problem is already superfluous when the previous problem is solved): 

I can write functions into this property by myself. I have implemented the component with the following function as a test: 

```    
<q-file v-model="upload" label="Label" :filter="(files) => checkFile(files, {... some properties here ...})">
</q-file>
```

But since I could not successfully implement the first case, I cannot test this case at all. Would such a construct work?

**Comment by jarvelov** [comment]
Hi,

The `:` is just the syntax Vue uses to figure out that the value within the quotes is something other than that a string, as in this case it's a function.

```js
{
    component: "q-file",
    model: "upload",
    fieldOptions: {
        props: {
          filter: this.checkFile,
          // Or
          filter: () => {
            // some action
          }
      }
   }
}
```

I have not tried this but I think it should work.

**Comment by janschoepke** [comment]
Hello and thank you very much for the quick answer. The solution you described works without any problems! Many thanks and sorry for the trouble!

**Comment by woutercouvaras** [comment]
Hi,

As in this example, I'm trying to pass a value down to a component, but for some reason I get an error (```TypeError: t.reduce is not a function```) (I am using Nuxt, so that error might not be relevant).

This only seems to happen with dynamic values (i.e. anything out of data or model).  Passing a string works fine.

I forked the components demo and updated it with a simple prop and it doesn't work there either (only if I set a string or number, right in the actual props object, does it work):

https://codesandbox.io/s/example-4-u17ik?file=/src/components/example-four.vue:4525-4559

I'm I trying to use this in an unintended way?

Many thanks in advance.

**Comment by woutercouvaras** [comment]
Not to worry, thanks to an answer @jarvelov gave in another issue, I managed to get it working.  The ```uiSchema``` needs to be defined as computed property...then all works just fine.  Here's the reference:

https://github.com/jarvelov/vue-form-json-schema/issues/16#issuecomment-470122640

Thanks for all your hard work @jarvelov !

**Comment by jarvelov** [comment]
Hi, if you want to use data properties in the `uiSchema` you have to either put the `uiSchema` as a property of `computed` or assign it to the `data` property in the `created` lifecycle method.

If you want the uiSchema value to be updated when the `this.testProp` value changes then you need to put the `uiSchema` as a property in `computed`.

Here is an example of using `computed`:

https://codesandbox.io/s/example-4-sy5wm?file=/src/components/example-four.vue

Here is an example of using `created`:

https://codesandbox.io/s/example-4-sy5wm?file=/src/components/example-four.vue

**Comment by woutercouvaras** [comment]
You're a legend!  Thanks!
