### ISSUE TITLE
Update demo links

### ISSUE THREAD

**Issue by maparaschivei** [jarvelov/vue-form-json-schema#5]
The demo links are no longer working as the domain for webpackbin.com has expired. 

Please refer to the following link for more information: https://github.com/cerebral/webpackbin

The "webpackbin" project has moved to: https://codesandbox.io

You can use the following links to see the old demo code:

- Minimal demo 
    - https://webpackbin-prod.firebaseapp.com/bins/-L0_48pIxbUFNG8f87pI
- Nested UI demo
    - https://webpackbin-prod.firebaseapp.com/bins/-L0_5kwqJixNYqtpiYxd
- Conditional visibility and Animation demo
    - https://webpackbin-prod.firebaseapp.com/bins/-L0hgoQjI7Cq2EibysRr

**Edit**

My apologies, I now see that this is a re-post of issue: #1

**Comment by jarvelov** [comment]
Thanks for a working version of the old demos! When the service went down I actually hadn't saved them anywhere (as I wrote them directly in webpackbin) so I felt a bit disheartened at writing them from scratch again. I migrated them over to codesandbox.io as you suggested and every demo is working again.
