### ISSUE TITLE
JSON schema oneOf and validation

### ISSUE THREAD

**Issue by alexravenna** [jarvelov/vue-form-json-schema#54]
So I'm trying to use a JSON schema that contains a `oneOf` along with your [Example 3 - Conditional visibility](https://k0q8wk946o.codesandbox.io/) to achieve a field with dynamic validation values, i.e. they change based on user input. This user input would be a dropdown, where the user selects from one of two values for the same property.

I've created a Codesandbox [here](https://codesandbox.io/s/vfjs-bootstrap-vue-oneof-7gk74) to try to replicate what I've written in my app, and while it isn't quite the same thing, it's as close as I can manage.

As you can see, both schemas in the `oneOf` contain the same properties, just with different validation limits. The conditional visibility works fine, but the validation error never changes, even after I enter a valid (or invalid) value into the text input:

![image](https://user-images.githubusercontent.com/29532881/83049916-05979400-a04c-11ea-97a6-d38065801e8e.png)

Is something like this fundamentally possible right now with VFJS and I'm maybe just doing it wrong? 😰 

What I have in my application code is similar and makes it one step further (I don't get that validation error), but the validation doesn't seem to run when selecting a different dropdown option, i.e. if the valid text already in the input box should be invalid due to the validation rules from the new dropdown selection, no validation error is thrown. Is this kind of "dynamic behavior" possible?

**Comment by jarvelov** [comment]
Hi Alex

Sorry that it's taken so long for me to get back to you. You've might have already arrived at a solution but anyways I figured I'd answer for any other people asking the same question. You probably figured this out already but `oneOf` most likely isn't what you're looking for here, for a couple of reasons, but I digress. If I change to `anyOf` and restructure a bit to the schema below it seems to me like it works as expected:

```js
{
  type: "object",
  required: [
    "firstName"
  ],
  properties: {
    firstName: {
      anyOf: [
        {
          type: "string",
          minLength: 4,
          maxLength: 20
        },
        {
          type: "string",
          minLength: 2,
          maxLength: 10
        }
      ]
    }
  }
```

However, this only kind of "fixes" the example from your sandbox as it doesn't take into account the value of the `validationOption`. I've put together a [sandbox here](https://codesandbox.io/s/vfjs-bootstrap-vue-oneof-pnpf8) which shows how to dynamically apply the dynamic behavior I think you're after.

```js
{
  type: "object",
  required: ["validationOption"],
  // The allOf keyword is a very important piece. Read more about it in the link below about conditions
  allOf: [
    {
      if: {
        // If validationOption === 'type1' then firstName's length must be > 4 and < 20
        properties: {
          validationOption: {
            const: "type1"
          }
        }
      },
      then: {
        required: ["firstName"],
        properties: {
          firstName: {
            type: "string",
            minLength: 4,
            maxLength: 20
          }
        }
      }
    },
    {
      // If validationOption === 'type2' then firstName's length must be > 2 and < 10
      if: {
        properties: {
          validationOption: {
            const: "type2"
          }
        }
      },
      then: {
        required: ["firstName"],
        properties: {
          firstName: {
            type: "string",
            minLength: 2,
            maxLength: 10
          }
        }
      }
    }
  ]
}
```


The schema is using `if/then` conditions to get the dynamic behavior. See more info about these conditions [here](https://json-schema.org/understanding-json-schema/reference/conditionals.html).
