### ISSUE TITLE
Re-display error message

### ISSUE THREAD

**Issue by woutercouvaras** [jarvelov/vue-form-json-schema#56]
Hi @jarvelov,

Thanks for the awesome component!

After working through a few of your examples, I've got everything working, thanks!  

I just have a quick question, but rather than type out a whole scenario, one can actually look at the behaviour of example 7.  In this example, if one submits, the form correctly shows the error messages.  With error messages on screen, if one adds a "first name" to the field, the form seems to instantly re-evaluate (which is great), but if one then removes that value again, the form doesn't re-evaluate.  Even if one submits the form again, that specific error message does not return.

This might be a daft question (if so, please forgive me), but how does one get an error message to re-display or somehow re-trigger the validation for a field?

Thanks in advance

**Comment by woutercouvaras** [comment]
Okay, I was being a dumbass 😬 

For anyone else that has a brain fart, like I did...

This was simply because, as indicated by the jsonschema docs, an empty string is still a valid string.  If you don't want this to be true, you'll need to add a ```minLength``` rule to your schema.  Here's an example:

```
schema: {
  type: 'object',
  required: ['user'],
  properties: {
    user: {
      type: 'object',
      required: ['fullName'],
      properties: {
        fullName: {
          type: 'string',
          minLength: 2
        },
      }
    }
  }
}
```

Note, that this is set in the schema.  Initially I tried to set this in the schema object, under ```displayOptions``` (within uiSchema), but this didn't give me the behaviour I expected (probably me being daft again).

I now have one other problem...

Again, looking at example 7, the "message" property is clearly not required and the codesandbox example works, but if I copy that exact example, the validation fails...requiring message.  Am I missing something here?  I've ensured that I installed the exact same version of vue-form-json-schema, but I still can't get it to "exclude" message.

What am I doing wrong?

**Comment by jarvelov** [comment]
Hi!

It seems like a bug in VFJS. The same behavior is present in the example 7 demo. I'll need to investigate further. It probably is related to how nested properties are handled.

I'll try to look into it tomorrow but you could try by making `message` a property directly at the root of the schema, as in example 6, rather than as a nested property if `user` as in example 7.

**Comment by woutercouvaras** [comment]
Hi!,

Thanks for the reply.  I'm glad it's not just me being daft :)

I'll give your suggestion a try and also take a look at the code to see if I can figure anything out.

**Comment by jarvelov** [comment]
I've tracked the bug down. Just gotta make sure it doesn't break anything else, but I hope to release it tomorrow in 2.5.4.

**Comment by woutercouvaras** [comment]
Wow!  Fantastic and well done!  I started taking a look at the code yesterday, but ran out of time.  Was it in this method by any chance?  https://github.com/jarvelov/vue-form-json-schema/blob/96a0f64105b91c9bcdd7e4dff61b4918b6608b24/src/vfjs-global-mixin/methods/vfjs-validation/getters.js#L33

Don't feel the need to answer, I can always check your next commit :)

Thanks again for looking into this so quickly...it's really appreciated!

**Comment by woutercouvaras** [comment]
Hi @jarvelov,

I hate to pester you.  I'm just checking in to find out how that testing went and when you think you might release that change.

Many tanks!

**Comment by jarvelov** [comment]
Hi @woutercouvaras 

Good news, I just released `v2.6.0` which includes the change. The error lies in an assumption I made 3 years ago about when a property was assumed to be required. I'm not sure if I remember exactly why but to keep it short I thought then that it would make sense for a property to be required when its parent was required if the model had a dot (`.`) in it. 

You can see the changes in these two commits:
* https://github.com/jarvelov/vue-form-json-schema/commit/5bcbd37fc55d64eb7108e74cf079ad72b343a753
* https://github.com/jarvelov/vue-form-json-schema/commit/3b410f3336ca4bac8bdbe97f9d7eead7776dfd99

**Comment by woutercouvaras** [comment]
Wonderful news!  Thank you so much!  I'm looking forward to getting stuck into using your lib.

Thanks again:)

**Comment by woutercouvaras** [comment]
Working like a dream.  Thank you!
