### ISSUE TITLE
issue with validation and @vue/composition-api

### ISSUE THREAD

**Issue by marcogh** [jarvelov/vue-form-json-schema#57]
hello, 

I've an issue with vfjs when using composition-api and dynamic form data loading:

[https://codesandbox.io/s/example-6-ui71x](https://codesandbox.io/s/example-6-ui71x)

after the setTimeout triggers, "valid" is still false.

where I am wrong?

**Comment by jarvelov** [comment]
Hi, thanks for opening this issue.

It seems like the validation isn't run when the model changes outside of VFJS. I've added a fix for this and will upload it in the next version, 2.5.4. I hope to upload it tomorrow.

**Comment by jarvelov** [comment]
Hi @marcogh 

It took me a few days but the new version is up now. It included some other changes so in the end it was released as `v.2.6.0`.
Let me know if you still have any issues.

**Comment by marcogh** [comment]
the issue is solved. thank you very much.
