### ISSUE TITLE
duplicate field id getting generated.

### ISSUE THREAD

**Issue by harish2704** [jarvelov/vue-form-json-schema#61]
Hi, 
First of all, thank you very much for this wonderful , simple, hack-able project.

I tried creating a component which can handle list of items using the mixins provided by this package.

during the testing, it is found that, the algorithm used for generating field id has some issues.  

That is, same "unique id" is generated for all items in an an array component.

It can be tested in this code sandbox demo . https://codesandbox.io/s/array-container-y446r 

This demo contains two lists ( one list inside another. )

add at-least two items into the list by clicking "add" button, and check the id parameter of similar input fields 

For eg: See the screen shot
![image](https://user-images.githubusercontent.com/1652903/88095683-20e9d000-cbb3-11ea-8c76-f0972552cbdf.png)

**Comment by jarvelov** [comment]
Hi,

Thank you for notifying me (and your subsequent pull request!). I'll close this issue so we can keep the discussion in the pull request: #62.
