### ISSUE TITLE
Latest UMD version not working in browser

### ISSUE THREAD

**Issue by nuykon** [jarvelov/vue-form-json-schema#8]
Uncaught ReferenceError: require is not defined -> module.exports = require("lodash/merge");

**Comment by jarvelov** [comment]
Confirmed. I'm looking into it.

**Comment by jarvelov** [comment]
This has now been fixed. Please see the [UMD demo](https://jsfiddle.net/jarvelov/ewg6dfqL/) for a working example.

**Comment by nuykon** [comment]
Thank You
