### ISSUE TITLE
Directive to UI component in UISchema

### ISSUE THREAD

**Issue by racs4** [jarvelov/vue-form-json-schema#80]
Hello, i'd like to know if there is any way of passing a directive to the custom component in the UISchema. I'm trying to use the directive of [this library](https://github.com/RonaldJerez/vue-input-facade) in one of my inputs; they got a `v-facade` directive which adds a mask to the input. I tried to pass this directive through the `attrs` and `props` on the `fieldOptions` object but this doesn't work. I couldn't find anything like that in the documentation or examples.

Congratulations for the great library.

**Comment by jarvelov** [comment]
Hi! I haven't added support for directives yet, however from a quick glance it should be very straight forward to implement. I'll look into it tonight.

**Comment by racs4** [comment]
Thanks for the response. I corrected my previous comment with the right libraries. 
In one of your examples there is a comment saying that fieldOptions has " `// Same API as Vue's render functions` ". In their [API](https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth) there is support for a directive property like this one: 

```
directives: [
    {
      name: 'my-custom-directive',
      value: '2',
      expression: '1 + 1',
      arg: 'foo',
      modifiers: {
        bar: true
      }
    }
],
```

I tried this: (`vs-input` is a component from [Vuesax](https://github.com/lusaxweb/vuesax) library and `facade` is a directive from [vue-input-facade](https://github.com/RonaldJerez/vue-input-facade) library)

```
uiSchema: [
        {
          component: "vs-input",
          model: "firstName",
          fieldOptions: {
            on: ["input"],            
            directives: [
              {
                name: "facade",
                value: '(##) #####-####',
              },
            ],
          },
        },
],
```

And worked!

Now there is only one little thing that i'm not understanding why is happening. The library `vue-input-facade` let you pass an array for multiple masks in one input (like this one: ` ['(##) #####-####', '(##) ####-####'' ]`). But when i pass an array for the `value` property of the directive object, i got a `[Vue warn]: You may have an infinite update loop in a component render function.`.  The component `<VueFormJsonSchemaFieldComponent>`  is shown at top of warning's stack. Any ideia why this is happening?

**Comment by jarvelov** [comment]
Hi,

You would need to set the `mask` as a property of the `modifiers` property. You can see an example here: https://codesandbox.io/s/py6611pr9m?file=/src/components/example-one.vue

```js
directives: [
 {
   name: "facade",
   modifiers: {
     mask: "(###) ###-####",
   },
 },
]
```

**Comment by racs4** [comment]
Thank you very much. Really, you helped me a lot. 
Congrats again.
