### ISSUE TITLE
Paused development until January 2021

### ISSUE THREAD

**Issue by jarvelov** [jarvelov/vue-form-json-schema#86]
Hi everyone who uses this library!

I have some personal things to take care of in the next few weeks and to make room for those things I have to pause development until the end of the year (2020). I'll try to read issues and answer if I can but it will probably take until sometime in January 2021 before I have the time to pick up development and support of VFJS again. I expect I'll be unavailable sometime around March 2021 as well, but it is still uncertain.

Hope to see you in 2021!

**Comment by eyleron** [comment]
@jarvelov hope all is well with you and yours!

**Comment by jarvelov** [comment]
Hi @eyleron

Thanks for checking in! I'm alive and well, although my schedule is, and has been for so many months now, packed with personal stuff. However I will be coming back to continue development little by little from now. There are 2 PRs I hope to release this week and starting next week I hope to make some progress on the Vue 3 version.
