### ISSUE TITLE
How to change a prop value from a parent component?

### ISSUE THREAD

**Issue by DavidBord** [jarvelov/vue-form-json-schema#91]
Hi,
I have a Vue component that adds to the uiSchema an md-button and a component that wraps md-dialog (from vue-material) that is not active by default. What I am trying to accomplish here, is when I click on the md-button, the component that wraps md-dialog becomes active.
I tried passing the value as a prop:
`
props: {
                    'show-dialog': this.model.sd
                  }
`
where
`this.model.sd = false`
And on the button click event set:
`this.model.sd = true`

But this didn't open the dialog.
I would appreciate your help here.

**Comment by jarvelov** [comment]
Hi David, most likely it is because your `uiSchema` is a `data` property, and thus it is not reactive. If so, then you can just move the property to `computed` and without any additional changes your code should work.

Let me know how things work out.

**Comment by DavidBord** [comment]
Works perfectly!
Thank you!

**Comment by DavidBord** [comment]
Hi,
I elaborated my use case and now in the top level Vue component I hold an object that holds the show dialog (sd from my first comment here) for each dialog that can be opened (there are several) - when I click on the button to display a certain dialog it does not do anything but if I close the current dialog and open current the dialog again then it also opens the nested dialog. I would appreciate your help here.

**Comment by DavidBord** [comment]
I resolved this issue by sharing the model between the button and the dialog and changing its state only through the return value of the `on` handlers
